In [1]:
#ignoring the warnings since tensor flow will give  a lot of them
import warnings
warnings.filterwarnings("ignore")

# Import required Libraries
import tensorflow as tensorflow

In [2]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator 

In [3]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D, Activation
from tensorflow.keras.preprocessing import image

In [14]:
!pip install opencv-python

In [4]:
# Loading the dataset
import matplotlib.pyplot as plt
import numpy as np
import os # To create paths and itreate through directories
import cv2 #image operations

In [9]:
# Load directories where data is located

# use '\'
train_dir= "training_set/training_set"
test_dir= "test_set/test_set"

Categories=["cats","dogs"]

# Now we create paths

#path=os.path.join(train_dir,i) will create the paths 
        #"C:\Users\AYAN\Desktop\DATA SCIENCE PG\MODULE 5\CLASS 2\test_set\test_set\cats" and
        #C:\Users\AYAN\Desktop\DATA SCIENCE PG\MODULE 5\CLASS 2\test_set\test_set\dogs
        
#image_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GREYSCALE) will create the paths
        #"C:\Users\AYAN\Desktop\DATA SCIENCE PG\MODULE 5\CLASS 2\test_set\test_set\cats\cat4001.jpg"
        #cv2.IMREAD_GREYSCALE converts image to grey scale(binary)
        
for i in Categories:
    path=os.path.join(train_dir,i) 
    for img in os.listdir(path):
        image_array=cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE) 
        plt.imshow(image_array,cmap='gray')
        plt.show()
        break
    break          
    
       
# due to the break statement we are able to see the pic. since we stoped in 1 itreation
        
                                 

In [10]:
print(image_array) # this is how the images are stored ie as 2d arrays

[[ 42  42  43 ... 201 196 195]
 [ 43  43  43 ... 197 193 191]
 [ 43  43  43 ... 193 192 192]
 ...
 [ 31  29  25 ...  26  33  49]
 [ 31  29  25 ...  32  36  47]
 [ 31  28  24 ...  41  34  32]]


In [13]:
# select a size for the image

im_size=50

#create new array with all images of this size
new_array=cv2.resize(image_array,(im_size,im_size))
plt.imshow(new_array,cmap='gray')
plt.show()

In [20]:
# Now we create the training dataset

training_data=[]

# create a function for this asnd copy paste the above commands
# the try catch block helps to prevent crashing of the code due to damaged files

def create_training():
    for i in Categories:
        path=os.path.join(train_dir,i) 
        class_num=Categories.index(i)# In this step we make cats as 0 and dog as 1
        
        for img in os.listdir(path):
            try:
                image_array=cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE) 
                new_array=cv2.resize(image_array,(im_size,im_size))
                training_data.append([new_array,class_num])

            except Exception as e:
                print("image is broken")
                    
create_training()                    

image is broken
image is broken


In [21]:
print(len(training_data))

8005


In [22]:
# Shuffle the dataset to mix uniformly

import random

random.shuffle(training_data)

In [23]:
# create x and y

x=[]
y=[]

for features,labels in training_data:
    x.append(features)
    y.append(labels)
    
# we need to make x as a numpy array 
import numpy as np
x=np.array(x).reshape(-1,im_size,im_size,1) 
# -1 indicates all values are taken(this is not explining shape)
# im_size to resize the array
# 1 to indicate grayscale if it was RBG, use 3 instead


In [24]:
# Now we save x and y
# this can be done by to_csv or by pickleing

import pickle

pickle_out=open("x.pickle","wb")
pickle.dump(x,pickle_out)
pickle_out.close()

pickle_out=open("y.pickle","wb")
pickle.dump(y,pickle_out)
pickle_out.close()

In [25]:
# to reuse this

pickle_in=open("x.pickle","rb")
x=pickle.load(pickle_in)

pickle_in=open("y.pickle","rb")
y=pickle.load(pickle_in)

In [26]:
x[0] # This is the feature array ie image

array([[[255],
        [255],
        [254],
        ...,
        [254],
        [254],
        [255]],

       [[255],
        [254],
        [251],
        ...,
        [251],
        [255],
        [255]],

       [[255],
        [255],
        [188],
        ...,
        [159],
        [255],
        [255]],

       ...,

       [[255],
        [252],
        [234],
        ...,
        [120],
        [177],
        [255]],

       [[255],
        [254],
        [250],
        ...,
        [195],
        [238],
        [255]],

       [[255],
        [255],
        [253],
        ...,
        [254],
        [254],
        [255]]], dtype=uint8)

In [27]:
y[0] # this is the label. 0 indicates cat

0

In [ ]:
# the pickled files can be used for further process